import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const LOCAL_API = "http://192.168.5.140:8000/api/v1";
const PROD_API =
	"https://api.obsidian-narrator.com/api/v1";

// Default to the public API so accidental builds are submission-safe.
// Local LAN testing: pnpm run build:local / deploy:local
const apiBaseUrl = process.env.NARRATOR_API_BASE_URL || PROD_API;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	define: {
		__NARRATOR_API_BASE_URL__: JSON.stringify(apiBaseUrl),
	},
});

console.log(`Narrator API base URL: ${apiBaseUrl}`);
if (!prod && apiBaseUrl === PROD_API) {
	console.log(`(dev tip) LAN build: NARRATOR_API_BASE_URL=${LOCAL_API} pnpm run dev`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
